version: "2"

services:
  sonarqube:
    image: lmanzoni/docker-sonarqube:7.0
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - /data/intesa/sonarqube-compose/sonarqube/conf:/opt/sonarqube/conf
      - /data/intesa/sonarqube-compose/sonarqube/data:/opt/sonarqube/data
      - /data/intesa/sonarqube-compose/sonarqube/extensions:/opt/sonarqube/extensions
      - /data/intesa/sonarqube-compose/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /data/intesa/sonarqube-compose/postgresql/postgresql:/var/lib/postgresql
      - /data/intesa/sonarqube-compose/postgresql/data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

